### ISSUE TITLE
why built this type of stupidity

### ISSUE THREAD

**Issue by iBabu007** [curbox-app/curbox-android#38]
I can't open my setting app nothing open and i can't disabled device admin access  cant uninstall.
Now Tell me solution.

**Comment by nethical6** [comment]
can you open the settings apps?

**Comment by nethical6** [comment]
if yes: Go to system>change date and time> and then change the date to next month. Open digipaws after this and device admin gets disabled.

if no: [boot into safe mode](https://www.androidauthority.com/how-to-enter-safe-mode-android-801476/), you will be able to uninstall the app or disable accessibility services

**Comment by nethical6** [comment]
also the app clearly mentions that once device admin is enabled it cannot be turned off for a month. Why did you turn it on so?.
it's your own fault. Stop complaining and Start reading things carefully. If it is of no use to you, doesn't mean it isn't for others. 🥰 
Reach me again if you're unable to uninstall it

**Comment by iBabu007** [comment]
Thanks bro.. You save me..
Your app is good and fullfil it's moto. but    
many bugs are present in it.
I can't open this app.
Whitelisted apps are also not open.

**Comment by nethical6** [comment]
> Thanks bro.. You save me.. Your app is good and fullfil it's moto. but many bugs are present in it. I can't open this app. Whitelisted apps are also not open.

yep, it's a known issue with adventure mode. You can use hard mode or easy mode alternatively, it's very stable

**Comment by iBabu007** [comment]
Ok.
Thanks again.
