### ISSUE TITLE
integrate weblate

### ISSUE THREAD

**Issue by avds2** [curbox-app/curbox-android#39]
Please add a way for it (:

**Comment by nethical6** [comment]
you can contribute and add your own language to the app

**Comment by nethical6** [comment]
check out this file:
https://github.com/nethical6/digipaws/blob/main/app/src/main/res/values/strings.xml

**Comment by nethical6** [comment]
you can watch tutorials on youtube to learn translating strings.xml file on android or even take help of something like chatgpt

**Comment by avds2** [comment]
Actualy I was talking about PO files or Weblate/Crowdin (: 
But OK, thanks.

**Comment by nethical6** [comment]
> Actualy I was talking about PO files or Weblate/Crowdin (:

oh, ohkay lmao
I already am planning to do it soon.
thanks.

**Comment by comradekingu** [comment]
I can help set up shop on the Hosted Weblate instance :)

**Comment by trindadedev13** [comment]
weblate whennnn

**Comment by nethical6** [comment]
> weblate whennnn

today

**Comment by nethical6** [comment]
now digipaws can be translated using weblate. https://hosted.weblate.org/projects/digipaws/
